name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Setup golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint --version

      - name: Run linter
        run: |
          golangci-lint run -E gocritic,revive ./...

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
